name: deploy mylog server to ec2

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            whoami

      - name: Pull Repository
        run: |
          cd /home/runner/work/mylog/mylog
          pwd
          ls -al
          sudo git pull origin main

      - name: Install dependencies
        run: |
          cd server
          sudo su
          sudo npm i

      - name: Check existing processes
        run: |
          sudo lsof -i :80
